<?xml version="1.0" encoding="UTF-8"?><!--
  ~ @(#)pom.xml
  ~ Copyright © 2023 Werner Randelshofer, Switzerland. MIT License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ch.randelshofer</groupId>
        <artifactId>org.monte.media.parent</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>org.monte.media.jpeg</artifactId>
    <packaging>jar</packaging>

    <name>Monte Media JPEG</name>
    <description>A library for processing JPEG images and EXIF metadata.</description>
    <build>
        <sourceDirectory>${basedir}/src/main/java/org.monte.media.jpeg</sourceDirectory>
        <testSourceDirectory>${basedir}/src/test/java/org.monte.media.jpeg</testSourceDirectory>
        <resources>
            <resource>
                <directory>${basedir}/src/main/java/org.monte.media.jpeg</directory>
                <excludes>
                    <exclude>**/*.java</exclude>
                </excludes>
            </resource>

        </resources>
        <testResources>
            <testResource>
                <directory>${basedir}/src/test/java/org.monte.media.jpeg</directory>
                <excludes>
                    <exclude>**/*.java</exclude>
                </excludes>
            </testResource>

        </testResources>

    </build>
    <dependencies>
        <dependency>
            <groupId>ch.randelshofer</groupId>
            <artifactId>org.monte.media</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-generator-annprocess</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
