/* @(#)package-info.java
 * Copyright © 2017 Werner Randelshofer, Switzerland. Under the MIT License.
 */
/**
 * Provides readers for the MPO file format.
 * <p>
 * Multi-picture File Format (MPO) as generated by the Fujfilm Real 3D W1 camera.
 * 
 * @author Werner Randelshofer
 * @version $Id: package-info.java 364 2016-11-09 19:54:25Z werner $
 */
package org.monte.media.mpo;

