/*
 * @(#)package-info.java
 * Copyright © 2025 Werner Randelshofer, Switzerland. MIT License.
 */
/// Provides readers for the MPO file format.
///
/// Multi-picture File Format (MPO) as generated by the Fujfilm Real 3D W1 camera.
///
/// @author Werner Randelshofer
package org.monte.media.mpo;

