/* @(#)package-info.java
 * Copyright © 2012 Werner Randelshofer, Switzerland.
 *
 * You may not use, copy or modify this file, except in compliance with the
 * license agreement you entered into with Werner Randelshofer. 
 * For details see accompanying license terms.
 */
/**
 * Provides media handlers for the MPO file format.
 * 
 * Multi-picture File Format (MPO) as generated by the Fujfilm Real 3D W1
 * camera.
 *
 * @author Werner Randelshofer
 * @version $Id: package-info.java 364 2016-11-09 19:54:25Z werner $
 */
package ru.sbtqa.monte.media.mpo;
